import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import waving from '../public/images/waving.png'
import Navbar from '../components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sam Brink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Navbar></Navbar>
      <main  className="bg-fadebluepurple w-full h-screen  flex items-center ">

<Image width={220} height={50} src={waving}></Image>
</main>
      </div>
   
 

    </>
  )
}
