import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import waving from '../public/images/waving.png'
import Navbar from '../components/Navbar'
import { useRef } from 'react'
const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const projectsRef = useRef(null)
  const skillsRef = useRef(null)
  const contactRef  = useRef(null)

  
  return (
    <>
      <Head>
        <title>Sam Brink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
<link rel="manifest" href="/site.webmanifest"/>
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
<meta name="msapplication-TileColor" content="#da532c"/>
<meta name="theme-color" content="#ffffff"/>

      </Head>
      <div>
      <Navbar
      contactRef={contactRef}
      skillsRef={skillsRef}
      projectsRef={projectsRef}
      ></Navbar>
      <main  className="bg-fadebluepurple w-full h-screen  flex items-center sm:justify-center ">

        <section className='mt-10 mx-5 flex flex-col  items-center gap-5 md:justify-center md:flex-row'>
          <div>
          <h2 className='text-4xl sm:text-5xl font-bold'> Hi I'm Sam</h2>
        <h3 className='text-2xl sm:text-3xl font-medium'> Software Developer</h3>
        <h7 className='text-xl  sm:text-2xl'> A creative developer with a strong passion for technology </h7>
          </div>
          <Image width={250} height={50} src={waving}></Image>


        </section>

  




</main>


<section ref={projectsRef}> 
  <h2 className='text-4xl mt-5 mx-5 font-medium'> Projects</h2>

</section>
      </div>
   
 

    </>
  )
}
